language: node_js
node_js:
- '10'
env:
  global:
  - CMS_IMAGE_NAME=luckjs/luck-cms
  - CMS_CONTAINER_NAME=luck-cms_master
  - DB_CONTAINER_NAME=luck-cms-db_master
  - VIRTUAL_HOST=cms.luck.org.pl
jobs:
  include:
  - stage: build
    services:
    - docker
    script:
    - docker build . -t $CMS_IMAGE_NAME
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $CMS_IMAGE_NAME
    env: CMS_IMAGE_NAME=$CMS_IMAGE_NAME
  - stage: deploy
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_cb7c2a716d0d_key -iv $encrypted_cb7c2a716d0d_iv
      -in .travis/id_rsa.enc -out .travis/id_rsa -d
    - eval "$(ssh-agent -s)"
    - cp .travis/id_rsa ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - ssh-keyscan $HOST_IP > ~/.ssh/known_hosts
    script: skip
    env:
    - CMS_IMAGE_NAME=$CMS_IMAGE_NAME
    - CMS_CONTAINER_NAME=$CMS_CONTAINER_NAME
    - DB_CONTAINER_NAME=$DB_CONTAINER_NAME
    - VIRTUAL_HOST=$VIRTUAL_HOST
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash .travis/deploy.sh $HOST_IP $DOCKER_PASSWORD $DOCKER_USERNAME $CMS_IMAGE_NAME
        $CMS_CONTAINER_NAME $DB_CONTAINER_NAME
      on:
        branch: master
